using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Darkstar;

/// <summary>An entry: if "Trigger" (substring, case-insensitive) is found in the transcribed
/// text, "Response" is used as the fixed reply - instead of the one generated by Gemini.</summary>
public sealed class PhraseEntry
{
    public string Trigger { get; set; } = "";
    public string Response { get; set; } = "";
}

/// <summary>
/// Loads/creates phrases.json: a list of fixed question/answer phrases (e.g. radio check) that
/// the bot answers directly, without a Gemini call. The actual Gemini call for transcription
/// still always happens (we need the recognized text to match the phrases against) - only the
/// reply generation gets replaced by the fixed phrase on a match.
/// </summary>
public static class PhraseBook
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.Never
    };

    public static List<PhraseEntry> LoadOrCreateDefault(string path)
    {
        if (!File.Exists(path))
        {
            var defaults = new List<PhraseEntry>
            {
                // No "radio check" entry: the bot answers that itself (see RadioCheck), and can add
                // whether it has the caller on scope - something a fixed phrase cannot know. An
                // entry added here still takes priority, for anyone who wants their own wording.
                new() { Trigger = "say again", Response = "Copy, say again your last transmission." },
                new() { Trigger = "status", Response = "All systems nominal." },
                new() { Trigger = "check in", Response = "Copy your check-in." },
                new() { Trigger = "request weather", Response = "Weather is clear, visibility unrestricted." },
                new() { Trigger = "request rtb", Response = "Copy, cleared to RTB." },
                new() { Trigger = "requesting rtb", Response = "Copy, cleared to RTB." },
            };

            var json = JsonSerializer.Serialize(defaults, JsonOptions);
            File.WriteAllText(path, json);

            Logger.Log($"No phrases.json was found. A new file with a sample entry was created: {Path.GetFullPath(path)}");
            Logger.Log("Additional fixed question/answer phrases can be added there following the same schema (Trigger/Response).");
            return defaults;
        }

        try
        {
            var text = File.ReadAllText(path);
            var entries = JsonSerializer.Deserialize<List<PhraseEntry>>(text, JsonOptions) ?? new List<PhraseEntry>();
            ValidateEntries(entries);
            return entries;
        }
        catch (JsonException ex)
        {
            // Without this catch, a JSON syntax error in phrases.json would crash the whole
            // process with an unhandled exception instead of failing gracefully.
            Logger.Log($"WARNING: phrases.json has a JSON syntax error and could not be parsed ({ex.Message}) - no fixed phrases will be used, all replies will go through Gemini.");
            return new List<PhraseEntry>();
        }
        catch (Exception ex)
        {
            Logger.Log($"WARNING: Could not read phrases.json ({ex.Message}) - no fixed phrases will be used, all replies will go through Gemini.");
            return new List<PhraseEntry>();
        }
    }

    /// <summary>Writes the phrase list back to path, backing up the previous version first.</summary>
    public static void Save(string path, List<PhraseEntry> entries)
    {
        BackupUtils.BackupBeforeWrite(path);
        var json = JsonSerializer.Serialize(entries, JsonOptions);
        File.WriteAllText(path, json);
    }

    /// <summary>
    /// Sanity-checks the loaded phrase list and logs a warning for anything that looks wrong
    /// (empty triggers/replies, duplicate triggers that would silently shadow each other). This
    /// never changes the list or stops the bot - it just makes problems visible in the log.
    /// </summary>
    private static void ValidateEntries(List<PhraseEntry> entries)
    {
        for (int i = 0; i < entries.Count; i++)
        {
            var entry = entries[i];
            if (string.IsNullOrWhiteSpace(entry.Trigger))
                Logger.Log($"WARNING: phrases.json - entry #{i + 1} has an empty Trigger and will never match.");
            if (string.IsNullOrWhiteSpace(entry.Response))
                Logger.Log($"WARNING: phrases.json - entry #{i + 1} (Trigger: \"{entry.Trigger}\") has an empty Response.");
        }

        var duplicateTriggers = entries
            .Where(e => !string.IsNullOrWhiteSpace(e.Trigger))
            .GroupBy(e => e.Trigger.Trim(), StringComparer.OrdinalIgnoreCase)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key);

        foreach (var trigger in duplicateTriggers)
            Logger.Log($"WARNING: phrases.json - Trigger \"{trigger}\" appears more than once; only the first occurrence will ever be used.");
    }

    /// <summary>
    /// Checks the transcribed text against all known triggers (substring search, case-insensitive).
    /// Returns the associated fixed reply on a match, otherwise null. The first matching entry
    /// in the list wins.
    /// </summary>
    public static string? TryMatch(string transcribedText, List<PhraseEntry> phrases)
    {
        if (string.IsNullOrWhiteSpace(transcribedText)) return null;

        var textLower = transcribedText.ToLowerInvariant();
        foreach (var entry in phrases)
        {
            if (string.IsNullOrWhiteSpace(entry.Trigger)) continue;
            if (textLower.Contains(entry.Trigger.ToLowerInvariant()))
                return entry.Response;
        }

        return null;
    }
}
